version: '3.9'
name: ms-arch

services:
  registry:
    build:
      context: ./registry
    container_name: registry
    networks:
      - skynet
    ports:
      - "3003:3000"  # Optional for debugging

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - registry
    networks:
      - skynet
    ports:
      - "3001:3000"

  client:
    build:
      context: ./leafDex_Web
    container_name: leafdex_web
    networks:
      - skynet
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://api-gateway:3000

networks:
  skynet:
    driver: bridge
