version: '3.8'

services:
  leafdex-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    restart: unless-stopped

  leafdex-web-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - ./leafDex_Web:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
